### ISSUE TITLE
Crash: random see stacktrace

### ISSUE THREAD

**Issue by endurance1968** [pulquero/BatteryAggregator#73]
Please include system details:

Version 3.2
Hardware: Cerbo

```
@4000000066f5b26c32b909ec INFO:com.victronenergy.battery.aggregator:DCL estimates: [3481.3180219316237, 410.6974931478565, 533.7958495626291, 392.5645022592769]
@4000000066f5bba90fa68204 CRITICAL:ve_utils:exit_on_error: there was an exception. Printing stacktrace will be tried and then exit
@4000000066f5bba90fa6b0e4 Traceback (most recent call last):
@4000000066f5bba90fa6b8b4   File "/data/BatteryAggregator/ext/ve_utils.py", line 22, in exit_on_error
@4000000066f5bba90fa6c46c     return func(*args, **kwargs)
@4000000066f5bba90fa6d024   File "/data/BatteryAggregator/ext/dbusmonitor.py", line 393, in _execute_value_changes
@4000000066f5bba90fa6dbdc     self.valueChangedCallback(serviceName, objectPath,
@4000000066f5bba90fa9a2cc   File "/data/BatteryAggregator/battery_service.py", line 538, in _service_value_changed
@4000000066f5bba90fa9b26c     self._battery_value_changed(dbusServiceName, dbusPath, options, changes, deviceInstance)
@4000000066f5bba90fa9c20c   File "/data/BatteryAggregator/battery_service.py", line 567, in _battery_value_changed
@4000000066f5bba90fa9d1ac     self._adjust_ir(dbusServiceName, current)
@4000000066f5bba90fa9d97c   File "/data/BatteryAggregator/battery_service.py", line 786, in _adjust_ir
@4000000066f5bba90faa567c     if current > 0:
@4000000066f5bba90faa5e4c TypeError: '>' not supported between instances of 'NoneType' and 'int'
@4000000066f5bbad313dd7b4 INFO:main:Starting...
```

happens sometimes not sure under which conditions

**Comment by pulquero** [comment]
Looks like for some reason, the current for a battery gets reported as null.
