### ISSUE TITLE
Issues after upgrading to 3.52~4 / 3.52~5 & 3.52~6

### ISSUE THREAD

**Issue by ewinkley** [pulquero/BatteryAggregator#79]
I've got a very simple system for testing / validation purposes as I build my off grid RV.  Issue started after upgrading to 3.52~4. I prefer using the BatteryAggregator as the main battery monitor due to the SmartShunt settings are not quite tuned properly.

**Environment:**
Cerbo GX 3.52~6
Two Renogy 100AH batteries, parallel, using venus-os_dbus-serialbattery
Victron SmartShunt 500A/50mV
Ruuvi temp monitor

**Setup:** 
SetupHelper, GuiMods, BatteryAggregator, TailScale, ShutdownMonitor

**dbus-spy output:**
com.victronenergy.adc                                                                                                                                                        
com.victronenergy.battery.ttyS7                                                                                                                            01 SmartShunt 500A
com.victronenergy.battery.ttyUSB0__0x30                                                                                                                             00 Batt 1
com.victronenergy.battery.ttyUSB0__0x31                                                                                                                             00 Batt 2
com.victronenergy.ble
com.victronenergy.digitalinputs
com.victronenergy.fronius
com.victronenergy.logger
com.victronenergy.modbusclient.tcp
com.victronenergy.modbustcp
com.victronenergy.packageManager                                                                                                                              Package Manager
com.victronenergy.platform                                                                                                                                              Venus
com.victronenergy.rvc.can0
com.victronenergy.settings
com.victronenergy.shutdown                                                                                                                                    ShutdownMonitor
com.victronenergy.system
com.victronenergy.tailscaleGX                                                                                                                             TailscaleGX-control
com.victronenergy.temperature.adc_builtin0_8                                                                                                                  01 Storage Temp
com.victronenergy.temperature.ruuvi_db7a5abe8277                                                                                                             02 Refridgerator
com.victronenergy.temprelay

Log attached with debug enabled, then disabled. 

**What I have tried:**
I uninstalled the BatteryAggregator, rebooted, then installed again from Package Manager, and with debug enabled it appeared to be functioning as I could see the two batteries, but then I had to reboot as often after a planned restart, the batteries are never found, and rebooting resolves this. I then disabled debug, rebooted and it's not working.

**non-debug log snippet:**
2024-11-18 16:02:43.449162500 INFO:main:Exit
2024-11-18 16:02:45.362957500 INFO:main:Starting...
2024-11-18 16:02:45.404515500 INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
2024-11-18 16:02:45.408716500 INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB0__0x30, scanning and storing items
2024-11-18 16:02:45.450017500 INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB0__0x30 has device instance 1
2024-11-18 16:02:45.458167500 INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB0__0x31, scanning and storing items
2024-11-18 16:02:45.505698500 INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB0__0x31 has device instance 4
2024-11-18 16:02:45.513854500 INFO:dbusmonitor:Found: com.victronenergy.settings, scanning and storing items
2024-11-18 16:02:46.090036500 INFO:dbusmonitor:       com.victronenergy.settings has device instance 0
2024-11-18 16:02:46.110522500 INFO:dbusmonitor:Found: com.victronenergy.system, scanning and storing items
2024-11-18 16:02:46.195667500 INFO:dbusmonitor:       com.victronenergy.system has device instance 0
2024-11-18 16:02:46.206315500 INFO:dbusmonitor:Found: com.victronenergy.battery.ttyS7, scanning and storing items
2024-11-18 16:02:46.225330500 INFO:dbusmonitor:       com.victronenergy.battery.ttyS7 has device instance 277
2024-11-18 16:02:46.235546500 INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
2024-11-18 16:02:47.943278500 INFO:main:Waiting for batteries (attempt 1 of 30)...
2024-11-18 16:02:47.995733500 INFO:com.victronenergy.battery.aggregator:Individual CCLs: {'com.victronenergy.battery.ttyUSB0__0x30': 50.0, 'com.victronenergy.battery.ttyUSB0__0x31': 50.0, 'com.victronenergy.battery.ttyS7': None}
2024-11-18 16:02:47.999693500 INFO:com.victronenergy.battery.aggregator:Connected batteries: ['com.victronenergy.battery.ttyS7']
2024-11-18 16:02:48.028183500 Traceback (most recent call last):
2024-11-18 16:02:48.028191500   File "/data/BatteryAggregator/battery_service.py", line 912, in wait_for_batteries
2024-11-18 16:02:48.028195500     batteryAggr.register(timeout=15)
2024-11-18 16:02:48.028197500   File "/data/BatteryAggregator/battery_service.py", line 402, in register
2024-11-18 16:02:48.028200500     self._batteries_changed()
2024-11-18 16:02:48.028202500   File "/data/BatteryAggregator/battery_service.py", line 551, in _batteries_changed
2024-11-18 16:02:48.028206500     self._updateCLs()
2024-11-18 16:02:48.028326500   File "/data/BatteryAggregator/battery_service.py", line 682, in _updateCLs
2024-11-18 16:02:48.028330500     self._updateCCL()
2024-11-18 16:02:48.028332500   File "/data/BatteryAggregator/battery_service.py", line 633, in _updateCCL
2024-11-18 16:02:48.028335500     currentRatios = self._get_current_ratios(connectedBatteries, aggr_allow.get_result())
2024-11-18 16:02:48.028339500   File "/data/BatteryAggregator/battery_service.py", line 581, in _get_current_ratios
2024-11-18 16:02:48.028365500     cap = aggr_cap.values.get(batteryName)
2024-11-18 16:02:48.028367500 AttributeError: 'NoneType' object has no attribute 'values'
2024-11-18 16:03:24.688173500 INFO:main:Exit
2024-11-18 16:03:30.994067500 INFO:main:Starting...
2024-11-18 16:03:31.039355500 INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
2024-11-18 16:03:31.043711500 INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB0__0x30, scanning and storing items
2024-11-18 16:03:31.077218500 INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB0__0x30 has device instance 1
2024-11-18 16:03:31.085045500 INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB0__0x31, scanning and storing items
2024-11-18 16:03:31.117954500 INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB0__0x31 has device instance 4
2024-11-18 16:03:31.126062500 INFO:dbusmonitor:Found: com.victronenergy.settings, scanning and storing items
2024-11-18 16:03:31.819462500 INFO:dbusmonitor:       com.victronenergy.settings has device instance 0
2024-11-18 16:03:31.837337500 INFO:dbusmonitor:Found: com.victronenergy.system, scanning and storing items
2024-11-18 16:03:31.896270500 INFO:dbusmonitor:       com.victronenergy.system has device instance 0
2024-11-18 16:03:31.902070500 INFO:dbusmonitor:Found: com.victronenergy.battery.ttyS7, scanning and storing items
2024-11-18 16:03:31.917875500 INFO:dbusmonitor:       com.victronenergy.battery.ttyS7 has device instance 277
2024-11-18 16:03:31.925873500 INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
2024-11-18 16:03:32.943532500 INFO:main:Waiting for batteries (attempt 1 of 30)...
2024-11-18 16:03:32.995184500 INFO:com.victronenergy.battery.aggregator:Individual CCLs: {'com.victronenergy.battery.ttyUSB0__0x30': 50.0, 'com.victronenergy.battery.ttyUSB0__0x31': 50.0, 'com.victronenergy.battery.ttyS7': None}
2024-11-18 16:03:32.999334500 INFO:com.victronenergy.battery.aggregator:Connected batteries: ['com.victronenergy.battery.ttyS7']
2024-11-18 16:03:33.028575500 Traceback (most recent call last):
2024-11-18 16:03:33.028585500   File "/data/BatteryAggregator/battery_service.py", line 912, in wait_for_batteries
2024-11-18 16:03:33.028589500     batteryAggr.register(timeout=15)
2024-11-18 16:03:33.028591500   File "/data/BatteryAggregator/battery_service.py", line 402, in register
2024-11-18 16:03:33.028594500     self._batteries_changed()
2024-11-18 16:03:33.028596500   File "/data/BatteryAggregator/battery_service.py", line 551, in _batteries_changed
2024-11-18 16:03:33.028600500     self._updateCLs()
2024-11-18 16:03:33.028729500   File "/data/BatteryAggregator/battery_service.py", line 682, in _updateCLs
2024-11-18 16:03:33.028734500     self._updateCCL()
2024-11-18 16:03:33.028735500   File "/data/BatteryAggregator/battery_service.py", line 633, in _updateCCL
2024-11-18 16:03:33.028739500     currentRatios = self._get_current_ratios(connectedBatteries, aggr_allow.get_result())
2024-11-18 16:03:33.028742500   File "/data/BatteryAggregator/battery_service.py", line 581, in _get_current_ratios
2024-11-18 16:03:33.028773500     cap = aggr_cap.values.get(batteryName)
2024-11-18 16:03:33.028777500 AttributeError: 'NoneType' object has no attribute 'values'

**Here is my config.json:**
{
  "excludedServices": [
    "com.victronenergy.battery.ttyS5"
  ],
  "primaryServices": [
    "om.victronenergy.battery.ttyUSB0__0x30",
    "om.victronenergy.battery.ttyUSB0__0x31"
  ],
  "capacity": 200
}
/data/setupOptions/BatteryAggregator/config.json (END)

**Debug logging enabled:**
[current.txt](https://github.com/user-attachments/files/17805524/current.txt)

**Comment by pulquero** [comment]
Should be ok now.
